#generated by ChaptGPT

def factorial(n):
    if n < 0:
        raise ValueError("Factorial is not defined for negative numbers")
    result = 1
    for i in range(2, n + 1):
        result *= i
    return result


if __name__ == "__main__":
    number = int(input("Enter a number to compute its factorial: "))
    try:
        result = factorial(number)
        print(f"Factorial of {number} is {result}")
    except ValueError as e:
        print(e)
