#generated by ChaptGPT

def factorial_iterative(n):
    result = 1
    for i in range(2, n + 1):
        result *= i
    return result

def factorial(n):
    if n < 0:
        raise ValueError("Factorial is not defined for negative numbers")
    return factorial_iterative(n)

# Example usage
if __name__ == "__main__":
    num = int(input("Enter a number: "))
    if num < 0:
        print("Factorial is not defined for negative numbers.")
    else:
        print(f"Factorial of {num} is {factorial_iterative(num)}")
